site_name: "VIAM Documention, Reference, and Tutorials"
nav:
  - Home: 'index.md'
  - Tutorials:
    - Install VIAM on Raspberry Pi: 'tutorials/install-on-pi.md'
    - Driving a Yahboom Rover with a Bluetooth Controller: 'tutorials/yahboom-rover.md'
