site_name: "VIAM Documention, Reference, and Tutorials"
nav:
  - Home: 'index.md'
  - Docs:
    - Viam's Design Principles: 'design-principles.md'
    - app.viam's Organizational Hierarchy: 'configuration-architecture.md'
    - app.viam's Robot Page: 'runtime-architecture.md'
    - Install VIAM on Raspberry Pi: 'tutorials/install-on-pi.md'
    - Viam's Robot Configuration: 'robo-config.md'
    - Viam's Application End-to-End Flow: 'end-to-end.md'
    - Viam's Authentication: 'authentication.md'
    - Viam Glossary: 'glossary.md'
    - Python SDK: 'https://python.viam.dev/'
theme:
  name: readthedocs
extra_css:
  - css/overrides.css
extra_javascript:
  - javascript/simple_auth.js
copyright: Copyright &copy; 2020 - 2022 Viam Robotics
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/viamrobotics/tutorials-and-docs/
      name: docs source on github
